name: simple_bank
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432" # actually not needed exposing to host, because api and migration will connect to it via docker network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d simple_bank" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    image: migrate/migrate:latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgresql://myuser:mypassword@postgres:5432/simple_bank?sslmode=disable"
      - "up"
    restart: "no"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://myuser:mypassword@postgres:5432/simple_bank?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SYMMETRIC_KEY=abcdefghijklmnopqrstuvwxyz123456
      - ACCESS_TOKEN_DURATION=15m
    depends_on:
      - migration
