// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `db:"id"`
	Owner     string             `db:"owner"`
	Balance   int64              `db:"balance"`
	Currency  string             `db:"currency"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type Entry struct {
	ID        int64              `db:"id"`
	AccountID int64              `db:"account_id"`
	Amount    int64              `db:"amount"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type Session struct {
	ID           int64     `db:"id"`
	SessionID    uuid.UUID `db:"session_id"`
	Username     string    `db:"username"`
	RefreshToken string    `db:"refresh_token"`
	UserAgent    string    `db:"user_agent"`
	ClientIp     string    `db:"client_ip"`
	IsBlocked    bool      `db:"is_blocked"`
	ExpiresAt    time.Time `db:"expires_at"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Transfer struct {
	ID            int64              `db:"id"`
	FromAccountID int64              `db:"from_account_id"`
	ToAccountID   int64              `db:"to_account_id"`
	Amount        int64              `db:"amount"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

type User struct {
	ID                int64              `db:"id"`
	Username          string             `db:"username"`
	HashedPassword    string             `db:"hashed_password"`
	FullName          string             `db:"full_name"`
	Email             string             `db:"email"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
}
